version: '3.8'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000

  backend:
    image: backend
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres