version: '3.8'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000

  backend:
    image: backend
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: redis
    restart: unless-stopped